name: Build and Push Docker Image

on:
  push:
    branches:
      - feature/build-and-publish-to-ecr

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
            AWS_ECR_REGISTRY_URL: ${{ secrets.AWS_ECR_REGISTRY_URL }}
            AWS_SECRET_LOGIN_PWD: ${{ secrets.AWS_SECRET_LOGIN_PWD }}
        run: |
          # Log in to AWS ECR
          echo $AWS_SECRET_LOGIN_PWD | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY_URL

          # Build and tag Docker image
          docker build -t hotel-reservation-system:latest .
          docker tag hotel-reservation-system:latest $AWS_ECR_REGISTRY_URL/hotel-reservation-system:latest

          # Push the Docker image to ECR repository
          docker push $AWS_ECR_REGISTRY_URL/hotel-reservation-system:latest
        if: success()

      - name: Dispatch CDK Deployment Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
            token: ${{ secrets.CDK_REPO_TOKEN }}
            repository: basting/hotel-reservation-system-cdk
            event-type: deploy-to-ecs-with-cdk
