name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint .

    - name: Build
      run: npm run build

    - name: Run unit tests
      run: npm test -- --coverage
      env:
        CI: true

    - name: Upload Clover Report
      uses: actions/upload-artifact@v2
      with:
        name: clover-report
        path: coverage/clover.xml
